package com.guxo.crmbackend.customer;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.guxo.crmbackend.appuser.AppUser;
import com.guxo.crmbackend.files.Image;
import com.sun.istack.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDate;

@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table
//@DynamicUpdate
public class Customer {
    // TODO reference to User who created
    // TODO customer photo

    // Required / Not generated by DB / Real ID from customer
    @Id
    @NotNull
    private Long id;

    // Required
    @NotNull
    private String name;

    // Required
    @NotNull
    private String surname;

    private String email;

    private LocalDate dateOfBirth;

    private String note;

    @JsonIgnore
    @ManyToOne(cascade = CascadeType.DETACH)
    private Image photo;

    @JsonIgnore
    @ManyToOne(cascade = CascadeType.DETACH)
    private AppUser creationAppUser;

    @JsonIgnore
    @ManyToOne(cascade = CascadeType.DETACH)
    private AppUser lastUpdateAppUser;


    public String getPhotoUrl(){
        if(photo == null){
            return null;
        }
        return photo.getUrl();
    }

    public String getCreationUser() {
        if(creationAppUser == null) {
            return null;
        }
        return creationAppUser.getUsername();
    }


    public String getLastUpdateUser() {
        if(lastUpdateAppUser == null) {
            return null;
        }
        return lastUpdateAppUser.getUsername();
    }
}
