package com.guxo.crm_backend.customer;

import com.sun.istack.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.time.LocalDate;

@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table
//@DynamicUpdate
public class Customer {
    // TODO reference to User who created
    // TODO customer photo

    // Required / Not generated by DB / Real ID from customer
    @Id
    @NotNull
    private Long id;

    // Required
    @NotNull
    private String name;

    // Required
    @NotNull
    private String surname;

    private String email;

    private LocalDate dateOfBirth;

    private String note;

    public Customer(Long id, String name, String surname) {
        this.id = id;
        this.name = name;
        this.surname = surname;
    }



}
