package com.guxo.crm_backend.customer;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.time.LocalDate;

@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@Entity
@Table
public class Customer {
    // TODO reference to User who created
    // TODO customer photo


    // Required / Not generated by DB / Real ID from customer
    @Id
    private Long id;

    // Required
    private String name;

    //Required
    private String surname;

    private String email;
    private LocalDate dateOfBirth;
}
