package com.guxo.crm_backend.customer;

import lombok.*;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import java.time.LocalDate;
import java.time.Period;

@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
@Setter
@Getter
@Entity
@Table
public class Customer {
    // TODO reference to User who created
    // TODO customer photo

    // Required / Not generated by DB / Real ID from customer
    @Id
    @NotNull(message = "ID is required")
    private Long id;

    // Required
    @NotNull(message = "Name is required")
    private String name;

    //Required
    @NotNull(message = "Surname is required")
    private String surname;

    @Email(message = "Invalid Email format")
    private String email;

    @Past(message = "Enter a valid past date")
    private LocalDate dateOfBirth;

    @Past(message = "Enter a valid past date")
    private LocalDate lastPurchase;

    public Customer(Long id, String name, String surname) {
        this.id = id;
        this.name = name;
        this.surname = surname;
    }

}
